#!/usr/bin/env python
# -*- coding: utf-8 -*-
import argparse
import logging
import re
import sys
from urlparse import urlparse

from bs4 import BeautifulSoup
import requests
from requests.exceptions import SSLError

logging.getLogger('requests').setLevel(logging.INFO)
logging.getLogger(__name__)
logging.basicConfig(stream=sys.stdout, level=logging.INFO)

parser = argparse.ArgumentParser(description='This script takes a url and a selector and prints items found to STDOUT')
parser.add_argument('url', type=str, help='url to parse')
parser.add_argument('selector', type=str, help='selector for elements to find')

args = parser.parse_args()


def prepare_match_for_output(match, url):
    content = match.get_text().encode('utf-8').strip()

    # If match has no text, return
    if not re.search(r'[a-zA-Z]', content):
        return None

    content = '\n' + re.sub(r'\s+', ' ', content)

    # Display url when searching for links
    if match.name == 'a':
        href = match.attrs.get('href','')
        parsed_ref = urlparse(href)

        if href and not parsed_ref.netloc:
            href = '{}{}'.format(url.netloc, href)
            content += '\n({})'.format(href)
        else:
            # Link without url
            return None

    return content


if __name__ == '__main__':
    url = args.url
    selector = args.selector

    if not 'http' in url:
        url = 'https://' + url

    target_url = urlparse(url)

    try:
        r = requests.get(target_url.geturl())
    except SSLError:
        logging.info('SSL error while attempting to https. Falling back to http')

        url = re.sub('https:', 'http:', url)
        target_url = urlparse(url)
        r = requests.get(target_url.geturl())

    soup = BeautifulSoup(r.text, 'html.parser')
    target_matches = soup.select(selector)
    final_content = set()

    for match in target_matches:
        content = prepare_match_for_output(match, target_url)

        if content:
            final_content.add(content.title())

    for content in sorted(final_content):
        print content
